# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication
from StartWindow import Ui_Form
from PyQt5.QtWidgets import QMainWindow


class End(QMainWindow, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = End()
    ex.show()
    sys.exit(app.exec_())